### ISSUE TITLE
Please help me sir .

### ISSUE THREAD

**Issue by purushottam858** [Dirk-Sandberg/theater-guide-pro#1]
I have seen your youtube videos and github projects , they are awesome . 

I am trying to contact you from long time , I did not get your email id or anything else  , so I dont have any other option  , I am messaging here  .
I am working on STARTUP  , I need to implement PUSH NOTIFICATION WITH FIREBASE CLOUD MESSAGING in android kivy app . I need your help,  I tried alot (with youtube videos ) but I am running into errors . 

I AM WILLING TO PAY  FOR YOUR HELP ,  PLEASE HELP ME OUT SIR . CONTACT ME HERE mekala.purushottam@gmail.com  , WILL WORK TOGETHER  AS PER YOUR TIMING .

**Comment by Dirk-Sandberg** [comment]
I suggest reaching out to the kivy discord channel, that would be the best spot to get help! https://chat.kivy.org/
